### ISSUE TITLE
Naming conflict with graphql gem?

### ISSUE THREAD

**Issue by rmosolgo** [Shopify/graphql-parser#5]
Hi, 

I was looking at using this to build a document for the `graphql` gem, but I hit a bit of a road block. Both `graphql` _and_ `graphql-parser` define `GraphQL::Field`. What do you think of defining constants within another namespace? For example, defining them under the `GraphQL::Parser` namespace would avoid conflicts in my case. 

I tried to do it myself (https://github.com/Shopify/graphql-parser/compare/master...rmosolgo:use-namespace) but it caused the test to fail in a way that I didn't understand. `GraphQL::Parser::Parse` was returning an instance of `GraphQL::Parser::AST` instead of `GraphQL::Parser::Document`, and I couldn't figure out why :disappointed: .

What do you think, is that feasible?

**Comment by pthrasher** [comment]
@rmosolgo I was able to get the tests passing in my branch while also moving nearly everything under the `GraphQL::Parser` namespace. Take a look: https://github.com/pthrasher/graphql-parser/tree/chore/move-to-lower-namespace

**Comment by dylanahsmith** [comment]
Definitely agree.  I opened https://github.com/Shopify/graphql-parser/pull/6 to make the suggested change

Sorry that no one was watching the repo for issues.
